// <auto-generated />
using System;
using CareerDataTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareerDataTool.Data.Migrations
{
    [DbContext(typeof(CareerDataToolDbContext))]
    [Migration("20251125203707_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareerDataTool.Domain.Enterprises.Enterprise", b =>
                {
                    b.Property<int>("EnterpriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnterpriseId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnterpriseId");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Job.JobVacancy", b =>
                {
                    b.Property<int>("JobVacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobVacancyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<string>("IdFromSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobLanguage")
                        .HasColumnType("int");

                    b.Property<int>("JobPlacePlaceID")
                        .HasColumnType("int");

                    b.Property<int>("JobRole")
                        .HasColumnType("int");

                    b.Property<int?>("JobRoleLevel")
                        .HasColumnType("int");

                    b.Property<int?>("JobWorkMode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlFromSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("WhenWasPublishedInSite")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WhenWasRegister")
                        .HasColumnType("date");

                    b.HasKey("JobVacancyId");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("JobPlacePlaceID");

                    b.ToTable("JobVacancies");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.Place", b =>
                {
                    b.Property<int>("PlaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceID"));

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.HasKey("PlaceID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("StateID");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWord", b =>
                {
                    b.Property<int>("KeyWordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyWordId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeyWordCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyWordId");

                    b.HasIndex("KeyWordCategoryId");

                    b.ToTable("KeyWords");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWordCategory", b =>
                {
                    b.Property<int>("KeyWordCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyWordCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyWordCategoryId");

                    b.ToTable("KeyWordCategories");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWordVariation", b =>
                {
                    b.Property<int>("KeyWordVariationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyWordVariationId"));

                    b.Property<int>("KeyWordId")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyWordVariationId");

                    b.HasIndex("KeyWordId");

                    b.ToTable("KeyWordVariations");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.WordToIgnore", b =>
                {
                    b.Property<int>("WordToIgnoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordToIgnoreId"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordLanguage")
                        .HasColumnType("int");

                    b.HasKey("WordToIgnoreId");

                    b.ToTable("WordsToIgnore");
                });

            modelBuilder.Entity("JobVacancyKeyWord", b =>
                {
                    b.Property<int>("KeyWordsKeyWordId")
                        .HasColumnType("int");

                    b.Property<int>("jobVacanciesJobVacancyId")
                        .HasColumnType("int");

                    b.HasKey("KeyWordsKeyWordId", "jobVacanciesJobVacancyId");

                    b.HasIndex("jobVacanciesJobVacancyId");

                    b.ToTable("JobVacancyKeyWord");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Job.JobVacancy", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Enterprises.Enterprise", "JobEnterprise")
                        .WithMany("JobVacancies")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerDataTool.Domain.Location.Place", "JobPlace")
                        .WithMany()
                        .HasForeignKey("JobPlacePlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobEnterprise");

                    b.Navigation("JobPlace");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.City", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Location.State", "CityState")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityState");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.Place", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Location.City", "PlaceCity")
                        .WithMany()
                        .HasForeignKey("CityID");

                    b.HasOne("CareerDataTool.Domain.Location.Country", "PlaceCountry")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.HasOne("CareerDataTool.Domain.Location.State", "PlaceState")
                        .WithMany()
                        .HasForeignKey("StateID");

                    b.Navigation("PlaceCity");

                    b.Navigation("PlaceCountry");

                    b.Navigation("PlaceState");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.State", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Location.Country", "StateCountry")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateCountry");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWord", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Words.KeyWordCategory", "Category")
                        .WithMany("KeyWords")
                        .HasForeignKey("KeyWordCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWordVariation", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Words.KeyWord", "ParentWord")
                        .WithMany("Variations")
                        .HasForeignKey("KeyWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentWord");
                });

            modelBuilder.Entity("JobVacancyKeyWord", b =>
                {
                    b.HasOne("CareerDataTool.Domain.Words.KeyWord", null)
                        .WithMany()
                        .HasForeignKey("KeyWordsKeyWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareerDataTool.Domain.Job.JobVacancy", null)
                        .WithMany()
                        .HasForeignKey("jobVacanciesJobVacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareerDataTool.Domain.Enterprises.Enterprise", b =>
                {
                    b.Navigation("JobVacancies");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Location.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWord", b =>
                {
                    b.Navigation("Variations");
                });

            modelBuilder.Entity("CareerDataTool.Domain.Words.KeyWordCategory", b =>
                {
                    b.Navigation("KeyWords");
                });
#pragma warning restore 612, 618
        }
    }
}
